[project]
name = "proxy"
version = "0.1.0"
description = "Proxy tools."
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
ws = [
    "websockets>=15.0.1",
]
vmess = [
    "cryptography>=45.0.5",
    "pycryptodome>=3.23.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
